### ISSUE TITLE
`CustomBlock#getDisplayName()` returns nothing for block with either `name` or `display_name` set.

### ISSUE THREAD

**Issue by Andre601** [LoneDev6/API-ItemsAdder#18]
I'm trying to get the name of a CustomBlock and display it inside a Adventure Component. But doing `Component.text(customBlock.getDisplayName())` does result in no text being displayed.

I tried both `name` and `display_name` in the Item Configuration:
```yaml
info:
  namespace: vanillaplus
items:
  bauxite_ore:
    name: "Bauxite Ore" # Also tried with "display_name"
    resource:
      material: PAPER
      generate: true
      texture: block/bauxite_ore.png
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
        drop_when_mined: false
        drop_on_silk_touch: true
        break_tools_blacklist:
          - WOODEN_PICKAXE
```
